version: '3.7'

services:
    mongodb:
        image: mongo:latest
        container_name: mongodb
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: citz_root
            MONGO_INITDB_ROOT_PASSWORD: citz_root
            MONGO_INITDB_DATABASE: citizens-db
        ports:
            - 27031:27017
        volumes:
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro