server:
  port: 0
  contextPath: /servicea
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres?useSSL=false
    username: db_a
    password: db_a
  jpa:
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      
management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: prometheus



citizen-service:
  #name: citizen-service
  name: ServiceD
  #url: http://localhost:7061
