server:
  port: 0
  context-path: /serviced
  
spring:
  data:
    mongodb:
      username: citz
      password: citz
      database: citizens-db
      port: 27031
      host: localhost

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: prometheus