server:
  port: 7029

spring:
  application:
    name: ConfigServerZipkinSample
  cloud:
    config:
      server:
        native:
          search-locations: file:D:/Projects/SpringBoot/SpringBoot-Zipkin/Config-Server-Files
  profiles:
    active: native